### ISSUE TITLE
Alert required when editing an event line item

### ISSUE THREAD

**Issue by kathcarruthers** [JMAConsulting/biz.jmaconsulting.lineitemedit#1]
The extension allows a user to modify the number of event tickets purchased as a line item, and a popup is displayed warning that a payment record is required.  
![image](https://user-images.githubusercontent.com/13468905/30986359-216528da-a461-11e7-9921-ea5b0161c873.png)
The updated number of participants is recorded in the event, but no information is collected about the additional attendee(s).  The event is configured to allow multiple attendees on a single contribution, and displays a profile for each when using the online registration.

![image](https://user-images.githubusercontent.com/13468905/30986260-d0665fee-a460-11e7-9240-f27c5a018f59.png)
Can a popup similar to the payment record appear to bring the editor to the event attendee profile?

**Comment by monishdeb** [comment]
@JoeMurray @kathcarruthers I have investigated if Civi allows a standalone form via which we can display a profile to register each additional participant, but there isn't. The form used to collect information for the additional participants during online event registration cannot be used in this case. To support that, we need to create a new form which will add multiple profile (configured for that event), via which we can fill in the details of additional participants. And then the link of this new form will be shown in the popup message. Please provide your feedback!!

**Comment by JoeMurray** [comment]
So we don't have funding to look after the new form, but the suggestion is a good one and it in many ways qualifies as a bug. So, we could put a Warning saying that if they proceed that the additional participant information will not be collected, and allow them to make the choice. What are the results? My guess is that some of the reporting might be wrong, perhaps waitlisting may break...anything else? @monishdeb is there a way currently to edit registrants that allows all of their information to be added properly? If so, we could provide an option as a button in warning to go there. What is your estimate for doing this the right way with a new form versus something along the lines of the suggested workaround?

In addition to the issues about collecting information from new registrants when the number is increased, ideally the system should allow registered participants to be selected for removal when the number of participants is decreased but not set to zero. Is there any support for than now, @monishdeb ? How much effort would that be?

**Comment by monishdeb** [comment]
@JoeMurray there is no other way in Civi to collect information of additional registrants via any backoffice form or participant action OR there is no option to edit/correct the information of additional participants for an existing registration. However, it's not necessary to collect information for additional registrants as here we just need to update the participant count, if qty is changed. Let me explain with an example:
1. Suppose there is an event price field - 'Fundraiser dinner - $800' that is configured with participant count 8.
2. A participant made an online registration and selected 'Fundraiser dinner'. As a result, respective ```civicrm_lineitem.participant_count = 8```. 
3. Now if admin edits the line-item and changes the ```qty``` to 2 then we need to ensure that it also updates the ```particiapnt_count``` to 16.

So workaround would be to send an alert on line-item edit if qty is changed, notifying the admin that participant count is changed to N. That's it.

**Comment by JoeMurray** [comment]
@monishdeb There are two use cases for registering multiple participants in same purchase. In one, the civicrm_lineitem.participant_count is greater than 1 and no info is collected on subsequent (n>=2) participants. In another, correct me if I am wrong, but multiple registrants with their profile info are collected and participant_count =1, and qty>1. I think we should display an alert indicating 'You are changing the number of registrants. Please add new registrants at Events > Register Event Registrant or remove registrants from Find Registrants results.' Please close when done.

**Comment by monishdeb** [comment]
The Line Item Editor is moved to https://lab.civicrm.org/extensions/lineitemedit. The new issue link for this ticket is  https://lab.civicrm.org/extensions/lineitemedit/-/issues/1
