### ISSUE TITLE
line item changes should update connected participant fee total

### ISSUE THREAD

**Issue by lcdservices** [JMAConsulting/biz.jmaconsulting.lineitemedit#10]
If you use the line item edit tool to modify a contribution connected to an event, the line item changes are properly reflected in the participant record, but the event total is not updated. That fee total is stored in the participant record, not derived from the line items, and would need to be updated separately.

![image](https://user-images.githubusercontent.com/366478/38626977-d00398aa-3d7b-11e8-903f-0e7cc22d460a.png)

**Comment by monishdeb** [comment]
Submitted PR https://github.com/JMAConsulting/biz.jmaconsulting.lineitemedit/pull/13

**Comment by monishdeb** [comment]
PR is tested and merged, hence closing this issue
