### ISSUE TITLE
Warning text and cancel / submit

### ISSUE THREAD

**Issue by kathcarruthers** [JMAConsulting/biz.jmaconsulting.lineitemedit#2]
1. When Cancel is selected on a line item the word "lineitem" should be "line item":
WARNING: Cancelling this line item will affect the related contribution and update the associated financial transactions. Do you want to continue? 

2. Because the buttons are answering "Do you want to continue?" it might be simpler to have the button labels be Yes and No rather than Cancel Item and Cancel.

![2017-09-28_16-20-07](https://user-images.githubusercontent.com/13468905/30988884-ca379b70-a469-11e7-93ec-e1ba60069c66.png)

3. Is it possible to make the Cancel dialogue smaller?  It takes up most of the visible screen.

**Comment by kathcarruthers** [comment]
The Edit item dialogue is much larger than necessary.
![image](https://user-images.githubusercontent.com/13468905/30990246-88f356fe-a46e-11e7-856d-d36587d8b69e.png)

**Comment by JoeMurray** [comment]
Let's do 1. Please check 3 and Edit dialog too big. @lcdservices do you have feedback on 2: we're using Cancel for financial actions everywhere in a different way than we use Cancel on dialog boxes throughout CiviCRM, and here where they both appear it's confusing.

**Comment by kathcarruthers** [comment]
It may be that my screen is too small.  I will check again on a bigger monitor when I get home on the weekend.

**Comment by lcdservices** [comment]
@JoeMurray I'd vote for retaining "cancel item" (which I think is pretty clear) and "close" -- which is where we've moved with button labels in other similar contexts.

**Comment by monishdeb** [comment]
@JoeMurray @kathcarruthers I have fixed 1. and 2. Here's the screenshot: 
![screen shot 2017-10-23 at 2 32 28 pm](https://user-images.githubusercontent.com/3735621/31880941-ac422a00-b7ff-11e7-9f0e-507ae9978254.png)

Re 3. issue is, when we open a popup (here edit/cancel lineitem dialog) within a popup (here backoffice contribution form) then it doesn't respect the CSS class ```small-popup``` provided to action link. This would take time to fix it, so I am keeping this issue open.

**Comment by JoeMurray** [comment]
@monishdeb ping re: 

> when we open a popup (here edit/cancel lineitem dialog) within a popup (here backoffice contribution form) then it doesn't respect the CSS class small-popup provided to action link. This would take time to fix it, so I am keeping this issue open.

If this is core, please create a core issue and work on it as medium priority.

**Comment by monishdeb** [comment]
The Line Item Editor is moved to https://lab.civicrm.org/extensions/lineitemedit. The new issue link for this ticket is  https://lab.civicrm.org/extensions/lineitemedit/-/issues/2
