### ISSUE TITLE
Line total is not updating

### ISSUE THREAD

**Issue by lcdservices** [JMAConsulting/biz.jmaconsulting.lineitemedit#22]
Since v2.0, there appears to be a bug -- when changing the unit price, the line total is not recalculated. See screencast: https://lcdservices.tinytake.com/sf/MzAzNTcxOF85MDk4Nzg0

**Comment by agileware-fj** [comment]
This is possibly fixed by PR #23

**Comment by lcdservices** [comment]
@agileware-fj confirmed -- that PR addresses this bug.

**Comment by JoeMurray** [comment]
Thanks, folks! Fix merged, closing this issue.
