### ISSUE TITLE
does this extension let me edit the status of the line item?

### ISSUE THREAD

**Issue by Upperholme** [JMAConsulting/biz.jmaconsulting.lineitemedit#29]
Wondering if this extension might be useful for me. Will it let me edit the status of a payment? Specifically I had an issue recently where I recorded a new payment against a contribution, and set the status to 'completed' where in fact it should have been 'pending', but couldn't change that.

**Comment by JoeMurray** [comment]
No, this extension is about what is purchased, not what is being paid.

I don't think this will help as it is not related to its intended behaviour, but as an unexpected byproduct it might work: https://github.com/JMAConsulting/biz.jmaconsulting.customcontribstatuses

Good luck.
