### ISSUE TITLE
Total Amount includes the Tax amount twice

### ISSUE THREAD

**Issue by madurak** [JMAConsulting/biz.jmaconsulting.lineitemedit#35]
Hi @JoeMurray,

When creating a membership the total amount shown on the line editor section is adding the tax amount twice as you can see here - https://nimb.ws/lMASmR

Tested on clean CiviCRM v5.7.5 and Line Item Editor v2.0.

**Replication Steps:**
https://nimb.ws/AfUNvV

Please can this be looked into.

Thanks.

**Comment by JoeMurray** [comment]
Monish, could you review this by end of next week?

**Comment by madurak** [comment]
Hi @monishdeb - Please can you let me know if you had a look at this? Thanks.
cc @JoeMurray

**Comment by madurak** [comment]
Hi @JoeMurray 
Any news on this? Would be good to know if this will be fixed?
Thanks

**Comment by monishdeb** [comment]
@madurak this bug is fixed by https://github.com/JMAConsulting/biz.jmaconsulting.lineitemedit/pull/36 hence I am closing this issue. Please reopen this ticket if the issue persist. Thanks!
