### ISSUE TITLE
Add participant information on line item listing

### ISSUE THREAD

**Issue by samuelsov** [JMAConsulting/biz.jmaconsulting.lineitemedit#39]
It is possible in CiviCRM to create a registration for several participants. 
It creates one single contribution with all the line items of all the participants which works well.
With lineitemedit, it's even possible to cancel some participant from the invoice by removing the line items.

In the database we have the information of which line item correspond to which participant and we are able to tweak the invoice to group the line item by participant.

Unfortunately, if we want to remove or change the invoice, we don't have enough information on the screen to edit the proper line items.
For example, in a 3 participants registration, if we want to remove one of the participant from the invoice, it's quite impossible to do:

![Screenshot_2019-07-05 Edit Contribution - no participant name](https://user-images.githubusercontent.com/372004/60733678-9688ec80-9f1b-11e9-94d6-f52dc2645ac0.png)

My idea is to change the display as below. It's harmless and quite easy to do (PR will follow):

![Screenshot_2019-07-05 Edit Contribution - with participant name](https://user-images.githubusercontent.com/372004/60733515-119dd300-9f1b-11e9-8dbe-93899ace2d04.png)

**Comment by monishdeb** [comment]
The Line Item Editor is moved to https://lab.civicrm.org/extensions/lineitemedit. The new issue link for this ticket is  https://lab.civicrm.org/extensions/lineitemedit/-/issues/39
