### ISSUE TITLE
Cannot edit total amount although I appear to be able to 

### ISSUE THREAD

**Issue by eileenmcnaughton** [JMAConsulting/biz.jmaconsulting.lineitemedit#4]
When I go to edit the total amount & save I get blocked by the message below & since I cannot edit the net amount I cannot save my change. If I choose to edit the line items it works fine & I would suggest the best option is simply to freeze the total amount field so it is clear that the way to edit the total is by editing the line items

![screenshot 2018-03-02 14 56 12](https://user-images.githubusercontent.com/336308/36879701-ea9fcf38-1e29-11e8-8cf1-a05ebf0e9a64.png)

**Comment by monishdeb** [comment]
Yes and we already had a discussion of freezing this total amount field  on edit page, as we are allowing user to edit line-item via a separate form.

**Comment by eileenmcnaughton** [comment]
Cool - so this is agreed but not hit anyone's priority?

**Comment by JoeMurray** [comment]
Still waiting on potential client to hear if they will be interested in funding this.

**Comment by monishdeb** [comment]
Closing it, as it has been covered by https://github.com/civicrm/civicrm-core/pull/11780

**Comment by eileenmcnaughton** [comment]
@monishdeb it's only frozen in core for some contributions though isn't it? ie. not simple contributions (although perhaps later that will be)
