### ISSUE TITLE
Should we block editing the total_amount when this is installed?

### ISSUE THREAD

**Issue by MegaphoneJon** [JMAConsulting/biz.jmaconsulting.lineitemedit#43]
When editing the line items, the total_amount is automatically updated, and financial items are created appropriately.

However, if you edit the total_amount WITHOUT changing the line items, you end up out of balance.  Let me know if you need further details here.

Is there a use case where someone would need to change the total_amount directly when this extension is installed?

**Comment by JoeMurray** [comment]
Reasonable question. Some might like previous behaviour of being able (as a convenience) to edit the contribution total_amount if there is only one line item, and to have any change in that amount reflected in a change to the single line item's amount. The rationale might be that it would be slightly faster. Against that is the anti-pattern of having different UX for changing the contribution total for single and multiple line items. 

There should be a validation to prevent the total_amount being edited, either for any number of line items or at least if there are more than one line items.

**Comment by monishdeb** [comment]
The Line Item Editor is moved to https://lab.civicrm.org/extensions/lineitemedit. The new issue link for this ticket is  https://lab.civicrm.org/extensions/lineitemedit/-/issues/43
