### ISSUE TITLE
Potential conflict with CiviDiscount

### ISSUE THREAD

**Issue by brucew2013** [JMAConsulting/biz.jmaconsulting.lineitemedit#46]
I installed this extension in CiviCRM v4.7.13 with CiviDiscount already installed  under Joomla v3.6.5 and received this error message upon completion:
> Some modules define permissions but the CMS cannot store them; cividiscount

Upon editing or deleting a line item the CiviCRM icon just spins and never completes. Please advise.

**Comment by JoeMurray** [comment]
@monishdeb could you diagnose this in terms of determining fix required this week. Thx

**Comment by brucew2013** [comment]
I did find this tidbit in the CiviCRM annuls.
CRM-12059 Support hook_civicrm_permissions on Joomla
(https://issues.civicrm.org/jira/browse/CRM-12059)

> If this feature is by an active extension on Joomla, then we currently display an alert: "Some modules define permissions, but the CMS cannot store them".

Others:
https://issues.civicrm.org/jira/browse/HR-97
https://github.com/eileenmcnaughton/nz.co.fuzion.extendedreport/issues/70
https://develop.tadpole.cc/plugins/civicrm/blob/1be00335014aa5ffd77a323aa20cc15b501c82e8/civicrm/CRM/Core/Config.php#L326

**Comment by brucew2013** [comment]
Update: If I let it sit for more than 5-10 minutes then refresh the page the edit does complete.

**Comment by brucew2013** [comment]
But it doesn't update the total either.

**Comment by seamuslee001** [comment]
Hi @brucew2013 

I just tested using

CiviCRM v5.21.1 and current master version of the line item editor and CiviDiscount v3.8.1 and Joomla v3.9.13 and i had no issues with editing line items. I note that i was on a single language install as well not sure if that is important or not.

I note that the core issue around adding permissions into Joomla was merged into 4.7.21

**Comment by monishdeb** [comment]
The Line Item Editor is moved to https://lab.civicrm.org/extensions/lineitemedit. The new issue link for this ticket is  https://lab.civicrm.org/extensions/lineitemedit/-/issues/46
