### ISSUE TITLE
Line items - do they really have to be whole numbers?

### ISSUE THREAD

**Issue by eileenmcnaughton** [JMAConsulting/biz.jmaconsulting.lineitemedit#5]
I note that there is a limitation to whole numbers of line items - is this something baked into CiviCRM since intuitively there are cases when partial units make sense

![screenshot 2018-03-02 14 57 06](https://user-images.githubusercontent.com/336308/36879798-5238dd38-1e2a-11e8-9805-d4bae058bdf7.png)

**Comment by JoeMurray** [comment]
@monish please evaluate the scope of change required to support a certain number of decimals in the schema - not a float! - and throughout the code in every place where there is a calculation, including in sales taxes and in the Canadian Sales Tax extension. We should aim to support this but may not be able to fund this internally soon.

**Comment by eileenmcnaughton** [comment]
schema for this field is DECIMAL(20,2) - I'm not sure if the code enforces whole numbers anywhere other than the form validator here

**Comment by eileenmcnaughton** [comment]
Note that I don't have a specific interest here - it was something I noticed while reviewing the extension & felt that the form was enforcing something the schema didn't & which I suspected was permitted elsewhere in the code

**Comment by monishdeb** [comment]
@eileenmcnaughton the validation error is a bit insufficient to expose the actual criteria. This is a scenario for selectable price fields (checkbox, select, radio) as in Civi there is no way we can have fractional quantity EXCEPT if its a text amount where we are allowed to enter fractional qty. So in later case you won't get this validation error.

**Comment by JoeMurray** [comment]
@monishdeb could you change the error message to read: Please enter a whole number quantity for this type of price field.

**Comment by monishdeb** [comment]
Sure that will clarify a bit more

**Comment by eileenmcnaughton** [comment]
isn't that example a text amount? (this is a while back & I don't recall it well now but the screenshot seems to be)

**Comment by monishdeb** [comment]
@eileenmcnaughton as per the code it doesn't seem so as in [here](https://github.com/JMAConsulting/biz.jmaconsulting.lineitemedit/blob/master/CRM/Lineitemedit/Form/Edit.php#L129) we are throwing validation if the corresponding price field doesn't allow to enter fractional qty identified by ```is_enter_qty = 0```. The above screenshot is when you tried to submit the Edit form after changing the qty to 2.5

**Comment by eileenmcnaughton** [comment]
ok...

**Comment by adixon** [comment]
I can confirm that at least in some cases you can use fractional amounts in line item quantity. In my experiment, I wasn't able to use a fractional number when I wasn't using a price set (i.e. it was using a magic hidden price set), but was able to when i used a price set. So I'm convinced you can close this issue.

**Comment by JoeMurray** [comment]
Thanks, @adixon
