### ISSUE TITLE
2 Drupal log messages with each new contribution entered

### ISSUE THREAD

**Issue by IowaBoy1** [JMAConsulting/biz.jmaconsulting.lineitemedit#56]
Drupal 7.72
CiviCRM 5.24.5
Edit Line Item 2.3

I just enabled the Edit Line Item extension yesterday.  Today was the first time entering contributions. In the Drupal logs I am getting 2 messages for every contribution we entered. 

Notice: Undefined index: id in CRM_Lineitemedit_Util::buildLineItemRows() (line 918 of .../sites/default/files/civicrm/extensions/biz.jmaconsulting.lineitemedit/CRM/Lineitemedit/Util.php).

They have the same message but a different location. 
Location:
1. ...civicrm/contact/view/contribution?snippet=4&priceSetId=3
--
2. .../civicrm/contact/view/contribution?reset=1&action=add&cid=3885&context=contribution&snippet=json

**Comment by monishdeb** [comment]
The Line Item Editor is moved to https://lab.civicrm.org/extensions/lineitemedit. The new issue link for this ticket is  https://lab.civicrm.org/extensions/lineitemedit/-/issues/56
