### ISSUE TITLE
First line item detail is lost when creating a new contribution

### ISSUE THREAD

**Issue by samuelsov** [JMAConsulting/biz.jmaconsulting.lineitemedit#57]
I've got this problem for a while and though v2.3 would solve this but no luck.

To reproduce :
1. Create a new contribution
2. Add several line item and submit
3. The total is good but if you go to edit again, the first line is lost

![Peek 06-10-2020 10-48](https://user-images.githubusercontent.com/372004/95218165-fd9dec80-07c1-11eb-801b-e73a97f33636.gif)

**Comment by JoeMurray** [comment]
Monish, could you look at this? Thx.

**Comment by monishdeb** [comment]
@samuelsov  I wasn't able to replicate the issue on latest stable version of CiviCRM and lineitem editor 2.3. Here's a screencast how I tried to replicate it: 
![2020-10-08_14-48-31](https://user-images.githubusercontent.com/3735621/95440069-15b66d00-0976-11eb-8444-0d339cf71e17.gif)

Also in your screencast I can see the 1st row defaults the line-total and unti total value as NaN.N which I wasn't able to replicate in my local, with shoreditch enabled. Seems like there might be some JS error sepecific to your site? Can you please let me know if you are getting any error on browser console?

**Comment by samuelsov** [comment]
@monishdeb Nope, no javascript errors but I start to believe it could be a conflict with something else. I'm going to close it for now and reopen if I find something more.

**Comment by samuelsov** [comment]
@JoeMurray @monishdeb Thanks for the time spent btw, it definitely help finding the cause of the problem!

**Comment by samuelsov** [comment]
@monishdeb So, there is a bug but it's an edge case. Apparently in my site, there are 2 results to the api call:
```
$priceFieldValue = civicrm_api3('PriceFieldValue', 'get', ['name' => 'contribution_amount']);
```
So the `$priceFieldValue['id']` is never defined.

In the database, the name are slighly different (uppercase) but the api doesn't seems to be case sensitive :
```sql
SELECT * FROM civicrm_price_field_value WHERE name = 'contribution_amount';
+----+----------------+---------------------+-------------+-------+-----------+--------+--------------------+----------------------+--------
| id | price_field_id | name                | amount      | count | max_value | weight | membership_type_id | membership_num_terms | is_defa
+----+----------------+---------------------+-------------+-------+-----------+--------+--------------------+----------------------+--------
|  1 |              1 | contribution_amount | 1.000000000 |  NULL |      NULL |      1 |               NULL |                 NULL |        
| 65 |             24 | Contribution_Amount | 1.000000000 |  NULL |      NULL |      1 |               NULL |                 NULL |        
+----+----------------+---------------------+-------------+-------+-----------+--------+--------------------+----------------------+--------
2 rows in set (0.000 sec)
```

We might want to do (untested):
```diff
diff --git a/CRM/Lineitemedit/Util.php b/CRM/Lineitemedit/Util.php
index 80273b8..6af0492 100644
--- a/CRM/Lineitemedit/Util.php
+++ b/CRM/Lineitemedit/Util.php
@@ -918,12 +918,12 @@ ORDER BY  ps.id, pf.weight ;
           }
           else {
             if ($rowNumber == 0) {
-              $priceFieldValue = civicrm_api3('PriceFieldValue', 'get', ['name' => 'contribution_amount']);
+              $priceFieldValue = civicrm_api3('PriceFieldValue', 'get', ['name' => 'contribution_amount', 'sequential' => 1]);
             }
             else {
-              $priceFieldValue = civicrm_api3('PriceFieldValue', 'get', ['name' => 'additional_item_' . $rowNumber]);
+              $priceFieldValue = civicrm_api3('PriceFieldValue', 'get', ['name' => 'additional_item_' . $rowNumber, 'sequential' => 1]);
             }
-            $form->setDefaults(["item_price_field_value_id[$rowNumber]" => $priceFieldValue['id']]);
+            $form->setDefaults(["item_price_field_value_id[$rowNumber]" => $priceFieldValue['values'][0]['id']]);
           }
         }
       }
```

Let me know if you want me to do a PR.

**Comment by monishdeb** [comment]
Hmm the idea behind using 'name' => 'contribution_amount' parameter is, as it is a reserved quick config priceFieldValue used for backoffice contribution.  But it's weird that API acts on case-insensitive name filter but its how the MySQL does a case-insensitive search with = operator on string, for more detail please check https://stackoverflow.com/questions/3936967/mysql-case-insensitive-select. So there is no other way to modifiy the API parameter to make a case-sensitive search on priceFieldValue.name. 

As an alternative I agree with your patch about considering the first occurance in the list by choosing the harcoded 0th index. But we can do the same via: 
```patch
diff --git a/CRM/Lineitemedit/Util.php b/CRM/Lineitemedit/Util.php
index c4c3b29..22f89e4 100644
--- a/CRM/Lineitemedit/Util.php
+++ b/CRM/Lineitemedit/Util.php
@@ -922,10 +922,10 @@ ORDER BY  ps.id, pf.weight ;
           }
           else {
             if ($rowNumber == 0) {
-              $priceFieldValue = civicrm_api3('PriceFieldValue', 'get', ['name' => 'contribution_amount']);
+              $priceFieldValue = civicrm_api3('PriceFieldValue', 'get', ['name' => 'contribution_amount', 'options' => ['limit' => 1, 'sort' => "id"]]);
             }
             else {
-              $priceFieldValue = civicrm_api3('PriceFieldValue', 'get', ['name' => 'additional_item_' . $rowNumber]);
+              $priceFieldValue = civicrm_api3('PriceFieldValue', 'get', ['name' => 'additional_item_' . $rowNumber, 'options' => ['limit' => 1, 'sort' => "id"]]);
             }
             $form->setDefaults(["item_price_field_value_id[$rowNumber]" => $priceFieldValue['id']]);
           }
```
Can you please submit a PR for this patch?

**Comment by monishdeb** [comment]
@samuelsov can you review my PR https://github.com/JMAConsulting/biz.jmaconsulting.lineitemedit/pull/60 ?

**Comment by monishdeb** [comment]
The Line Item Editor is moved to https://lab.civicrm.org/extensions/lineitemedit. The issue link for this ticket is  https://lab.civicrm.org/extensions/lineitemedit/-/issues/57
