### ISSUE TITLE
Compatible with 4.6?

### ISSUE THREAD

**Issue by jaapjansma** [JMAConsulting/biz.jmaconsulting.lineitemedit#7]
Is this extension compatible with CiviCRM version 4.6? And if not what is needed to get it working on 4.6?

**Comment by jaapjansma** [comment]
I have tried it out and see that the Order API is required which is not present in 4.6

**Comment by jaapjansma** [comment]
It also requires Civi::Settings

**Comment by jaapjansma** [comment]
I can fix the order api in a seperate extension. But not sure about the Civi::Settings

**Comment by jaapjansma** [comment]
I will have a better look tomorrow. And will try to fix the breaking points.

**Comment by JoeMurray** [comment]
@eileen would know about settings stuff.

**Comment by jaapjansma** [comment]
I have also discovered another issue which I will try to fix. It comes down to the fact that the client for whom I am trying this out has line items attached to activities (based on the time spent on that activity). That is custom development for this client specific but this extension assumes the line items coming down from events or memberships. I will also try to fix that issue.

**Comment by JoeMurray** [comment]
Oh, interesting use of line items to link them to activities. PR would be welcome - we'll help with review and QA. Cheers.

**Comment by jaapjansma** [comment]
@JoeMurray unfortenatly I dont have any funding to fix the 4.6 issues. The project is on hold for the moment and I dont know when it will resume.

**Comment by JoeMurray** [comment]
Reviewing now I see I didn't respond to your original question. We would welcome PRs to support 4.6 but have no plans to add it ourselves.

Please reopen if you get resources to submit PRs for 4.6.
