### ISSUE TITLE
$0 value line items should be allowed

### ISSUE THREAD

**Issue by lcdservices** [JMAConsulting/biz.jmaconsulting.lineitemedit#8]
There is a form rule in place here:
https://github.com/JMAConsulting/biz.jmaconsulting.lineitemedit/blob/master/CRM/Lineitemedit/Form/Add.php#L100

...which prevents line item totals of $0. but that is a legitimate value -- both in the construction of price sets for events, and in the case where a discount is extended on a line item that normally would have a value. is there a reason that rule is in place?

**Comment by JoeMurray** [comment]
Some people/orgs object to them and consider them a bug. I agree they should be allowed.

**Comment by JoeMurray** [comment]
@monish could you fix? Thx

**Comment by monishdeb** [comment]
Submitted PR https://github.com/JMAConsulting/biz.jmaconsulting.lineitemedit/pull/11

**Comment by monishdeb** [comment]
PR is tested and merged, hence closing this issue
