### ISSUE TITLE
unit price for text fields should be modifiable

### ISSUE THREAD

**Issue by lcdservices** [JMAConsulting/biz.jmaconsulting.lineitemedit#9]
There is currently a form rule that prevents you from modifying the unit price for text fields. I think that should be allowed.

Let's say you have an event where there is a banquet you're selling tickets for and use the text field type to allow people to purchase multiple tickets. For a VIP attendee, you want to offer them a discount on the unit price for those tickets so you edit the line item (or add a new one) and want to adjust the unit price. The form rule currently prevents you from doing that.

I think the ability to adjust unit pricing for line items is one of the big features of this extension and should be allowed. This is also how CiviDiscount handles price adjustments, so I suspect the current behavior would conflict (e.g. if you try to edit a line item that was adjusted via CiviDiscount, it would likely throw the validation error).

**Comment by monishdeb** [comment]
Submitted PR https://github.com/JMAConsulting/biz.jmaconsulting.lineitemedit/pull/12

**Comment by monishdeb** [comment]
Closing it, as the PR is merged
